### ISSUE TITLE
Always checked the first card on the list issue

### ISSUE THREAD

**Issue by pszarzec** [tabdeck/tabdeck.so#53]
Hi, first of all, thanks for the great tool!

In Chrome (108.0.5359.125) I have a problem with the first tab in the list, it is always selected.
This tab is not in any group but it is pinned. It doesn't matter if I hard refresh the page, detach the card and pin it back.

![image](https://user-images.githubusercontent.com/3410380/210357434-7ca148db-8910-41c0-8c1e-d479bf2e24a6.png)

Some errors from Chrome console:

![image](https://user-images.githubusercontent.com/3410380/210358284-d4aa9311-e5da-4697-a0d4-232c551825a9.png)

If additional information is needed, please let me know.

**Comment by xiaoluoboding** [comment]
first of all, back up your data

Reactivate OTG Extension, and try again

**Comment by pszarzec** [comment]
@xiaoluoboding thanks, reactivated(off/on) helped!

**Comment by xiaoluoboding** [comment]
Try not hard refresh the page frequently, and I will try to fix this occasional problem
